{% set name = "gmailsorter" %}
{% set version = "0.1.4" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gmailsorter-{{ version }}.tar.gz
  sha256: fff702e521c732933610c4fe88759285e5db5bf44f45d15bb33842b30aa5dd52

build:
  entry_points:
    - gmailsorter=gmailsorter.__main__:command_line_parser
    - gmailsorter-daemon=gmailsorter.daemon.__main__:command_line_parser
    - gmailsorter-app=gmailsorter.webapp.app:run_app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - google-api-python-client >=2.176.0
    - google-auth >=2.40.3
    - google-auth-oauthlib >=1.2.2
    - numpy >=2.2.4
    - tqdm >=4.67.1
    - pandas >=2.3.1
    - scikit-learn >=1.6.1
    - sqlalchemy >=2.0.41

test:
  imports:
    - gmailsorter
  commands:
    - pip check
    - gmailsorter --help
    - gmailsorter-daemon --help
    # - gmailsorter-app --help
  requires:
    - pip
    # - flask <3
    # - flask-login
    # - werkzeug <3
    - python {{ python_min }}

about:
  home: https://github.com/jan-janssen/gmailsorter
  summary: Assign labels to emails in Google Mail based on their similarity to other emails assigned to the same label.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
