{% set name = "gmailsorter" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gmailsorter-{{ version }}.tar.gz
  sha256: 655eae89ebc3beef51b8b5d2df17381cf39dd5763560b158462f271a8406b1c0
  patches:
    - webapp.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - gmailsorter = gmailsorter.__main__:command_line_parser
    - gmailsorter-app = gmailsorter.webapp.app:run_app
    - gmailsorter-daemon = gmailsorter.daemon.__main__:command_line_parser

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - google-api-python-client >=2.92.0
    - google-auth >=2.21.0
    - google-auth-oauthlib >=1.0.0
    - numpy >=1.25.1
    - pandas >=2.0.3
    - python >=3.7
    - scikit-learn >=1.3.0
    - sqlalchemy >=2.0.18
    - tqdm >=4.65.0
    - gunicorn >=20.1.0
    - flask >=2.3.2
    - flask-login >=0.6.2

test:
  imports:
    - gmailsorter
  commands:
    - pip check
    - gmailsorter --help
    - gmailsorter-daemon --help
  requires:
    - pip

about:
  home: https://github.com/jan-janssen/gmailsorter
  summary: Assign labels to emails in Google Mail based on their similarity to other emails assigned to the same label.
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
