{% set name = "gmailsorter" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gmailsorter-{{ version }}.tar.gz
  sha256: f310c1419eebc845f218cbe315d540ce1f27ca429fc2b4716616bc52d94b96bf

build:
  entry_points:
    - gmailsorter=gmailsorter.__main__:command_line_parser
    - gmailsorter-daemon=gmailsorter.daemon.__main__:command_line_parser
    - gmailsorter-app=gmailsorter.webapp.app:run_app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - google-api-python-client >=2.102.0
    - google-auth >=2.23.2
    - google-auth-oauthlib >=1.1.0
    - numpy >=1.26.0
    - tqdm >=4.66.1
    - pandas >=2.1.1
    - scikit-learn >=1.3.1
    - sqlalchemy >=2.0.21

test:
  imports:
    - gmailsorter
  commands:
    - pip check
    - gmailsorter --help
    - gmailsorter-daemon --help
    - gmailsorter-app --help
  requires:
    - pip
    - flask
    - flask-login

about:
  home: https://github.com/jan-janssen/gmailsorter
  summary: Assign labels to emails in Google Mail based on their similarity to other emails assigned to the same label.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
