{% set name = "gmailsorter" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gmailsorter-{{ version }}.tar.gz
  sha256: d786e02b7de1d6885f5f892b7324f14c65a81582bebea236370af22b24b69646

build:
  entry_points:
    - gmailsorter=gmailsorter.__main__:command_line_parser
    - gmailsorter-daemon=gmailsorter.daemon.__main__:command_line_parser
    - gmailsorter-app=gmailsorter.webapp.app:run_app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - google-api-python-client >=2.117.0
    - google-auth >=2.27.0
    - google-auth-oauthlib >=1.2.0
    - numpy >=1.26.4
    - tqdm >=4.66.1
    - pandas >=2.2.0
    - scikit-learn >=1.4.0
    - sqlalchemy >=2.0.25

test:
  imports:
    - gmailsorter
  commands:
    - pip check
    - gmailsorter --help
    - gmailsorter-daemon --help
    # - gmailsorter-app --help
  requires:
    - pip
    # - flask <3
    # - flask-login
    # - werkzeug <3
    - python {{ python_min }}

about:
  home: https://github.com/jan-janssen/gmailsorter
  summary: Assign labels to emails in Google Mail based on their similarity to other emails assigned to the same label.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
